Fix "Activity class {/mnt/sdcard/jetpack-profile} does not exist" issue
'''
Starting: Intent { act=android.activity.MAIN cmp=/mnt/sdcard/jetpack-profile (has extras) }
Error type 3
Error: Activity class {/mnt/sdcard/jetpack-profile} does not exist.
'''